name: KompasAccountKitGenerated
include:
  - project.yml
options:
  bundleIdPrefix: id.kompas.app.account
packages:
  Yams:
    url: 'https://github.com/jpsim/Yams'
    from: 2.0.0
targets:
  KompasAccountKit:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - Sources
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: debug
        release:
          CUSTOM_BUILD_SETTING: release

  #   dependencies:
  #     - target: MyFramework
  #     - carthage: Alamofire
  #     - framework: Vendor/MyFramework.framework
  #     - sdk: Contacts.framework
  #     - sdk: libc++.tbd
  #     - package: Yams
  # MyFramework:
  #   type: framework
  #   platform: iOS
  #   sources: [MyFramework]

referensi
https://medium.com/@daviddvd19/xcodegen-first-steps-%EF%B8%8F-a2d4655ced86
https://medium.com/@daviddvd19/xcodegen-getting-deeper-2932474a5b59
https://github.com/daviwiki/article-xcodegen-gettingdeeper